### PR TITLE
Add implication concise form

### PR DESCRIPTION
**Pull request by Conaclos**
Hi!

This PR adds the concise form for the math implication.

### CODE REVIEW

**Comment by mattdesl** [comment]
Not sure I understand.

This code is saying "If A is true, then B must also be true."

```js
if (A === true) {
  console.assert(B === true)
}
```

However this has a lot of different implications in JavaScript:

```js
! A || B
```

If `A` does not *not* [coerce to a truthy value](http://www.sitepoint.com/javascript-truthy-falsy/) OR if `B` coerces to a truthy value.

**Comment by Conaclos** [comment]
A === false || B === true coule fix the coerce issue?

Accoridng me,
```js
if (A === true) {
  console.assert(B === true)
}
```

is equivalent to:

```js
console.assert(A === false || B === true)
```

**Comment by mattdesl** [comment]
They are similar but not exactly the same. Also I think simplicity is best here, rather than overwhelming the reader with alternatives. :smile: 

See the Wikipedia note [here](https://en.wikipedia.org/wiki/List_of_mathematical_symbols).

> A ⇒ B means if A is true then B is also true; **if A is false then nothing is said about B.**

The goal of my original code was to convey that nothing is said about B when A is false.

**Comment by Conaclos** [comment]
Ok. This is convincing :)

**Pull request closed without merging**
