### PR TITLE
Unicode rampage step 1

### PR DESCRIPTION
**Pull request by StoneCypher**

### CODE REVIEW

**Comment by mattdesl** [comment]
image

Unfortunately this renders as boxes on iOS.

**Comment by StoneCypher** [comment]
lol apple

god damnit

**Comment by StoneCypher** [comment]
i mean i'm pretty sure my palm pilot got unicode simple math (that's just bold letters and the hollow ring) right

that's borderline embarrassing, given their commitment to food emoji

**Comment by StoneCypher** [comment]
it seems like github ought to supply that font.

i wonder if i can go open an issue somewhere

**Comment by mattdesl** [comment]
Pretty happy with SVG. Will revisit this later if it becomes an issue.

**Pull request closed without merging**
