### PR TITLE
Added quantifiers

### PR DESCRIPTION
**Pull request by LOZORD**
At @daveloyall's request, I've added mathematical quantifiers.

### CODE REVIEW

**Comment by mattdesl** [comment]
Thanks @LOZORD, appreciate this. :tada: 

I'm going to review these and see how best to merge.

**Comment by mattdesl** [comment]
So I took a look through it, here are my thoughts.

- So far I've been trying to introduce only one (or two) symbols at a time. Then, later sections can build on those symbols to introduce other topics that might use them.
- I've also been trying to explain symbols immediately after using them; for example, the ∀ and ∃ are not explained in your PR until a few paragraphs later.
- Statements like *"take a college-level math course..."* are a bit disheartening to readers since it implies math can only be taught in formal education systems

Once I merge #25 I will revisit this and see where to fit it in, since there is some related concepts like number sets and logic symbols. :+1:

**Comment by LOZORD** [comment]
Ok, thanks for letting me know. Anything I can take care of in the meantime?

**Comment by mattdesl** [comment]
I've merged some of the logic stuff that will help beginners better understand your quantifiers section. I'm still hesitant to merge as the listed equation includes a subset character which has not yet been explained. 

If you wanted to change things, I would suggest simplifying it a bit *or* explaining the subset character (perhaps as a sub-section in *element of*). Also I would recommend explaining the new symbols immediately after showing them, and rewording the "Take a college course" to something more like "For more info on X, see [some link]". 

Just keep in mind, to anybody who isn't familiar with all of these symbols, it's really overwhelming to see an equation with several new features. It's better to try and parse the symbols one baby step at a time. :smile: 

Apologies for these nitpicks. Alternatively; if you don't feel like making changes I will eventually pull in your PR (maybe after I add a small section on the subset symbol) and tweak it to my needs. Thanks! :+1:

**Pull request closed without merging**
